name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check w/o SNAPSHOT when "bump version"
      if: ${{ contains(github.event.head_commit.message, 'bump version') }}
      run: grep "<version>" pom.xml | head -1 | grep -v SNAPSHOT

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      env:
        TEST_ACCOUNT : ${{ secrets.TEST_ACCOUNT }}
        TEST_PASSWORD : ${{ secrets.TEST_PASSWORD }}
        TEST_CLIENT_ID : ${{ secrets.TEST_CLIENT_ID }}
        TEST_CLIENT_SECRET : ${{ secrets.TEST_CLIENT_SECRET }}
        TEST_REDIRECT_URL : ${{ secrets.TEST_REDIRECT_URL }}
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
